import numpy as np
import pandas as pd
import torch 
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import os 
import sys
import glob

countries_mapping = {
    "N/A": 0,
    "Argentina": 1,
    "Australia": 2,
    "Austria": 3,
    "Budapest": 4,
    "Chile": 5,
    "China": 6,
    "Colombia": 7,
    "Czech Republic": 8,
    "Denmark": 9,
    "Ecuador": 10,
    "Egypt": 11,
    "France": 12,
    "Germany": 13,
    "Ghana": 14,
    "Greece": 15,
    "Hong Kong": 16,
    "Hungary": 17,
    "Iceland": 18,
    "India": 19,
    "Ireland": 20,
    "Italy": 21,
    "Japan": 22,
    "Jordan": 23,
    "Kazakhstan": 24,
    "Kenya": 25,
    "Madagascar": 26,
    "Mexico": 27,
    "Mongolia": 28,
    "Morocco": 29,
    "Nepal": 30,
    "Netherlands": 31,
    "New Zealand": 32,
    "Panama": 33,
    "Peru": 34,
    "Portugal": 35,
    "South Africa": 36,
    "South Korea": 37,
    "Spain": 38,
    "Sweden": 39,
    "Switzerland": 40,
    "Taiwan": 41,
    "Tanzania": 42,
    "Trinidad & Tobago": 43,
    "Turks & Caicos Islands": 44,
    "Turks and Caicos Islands": 45,
    "United Kingdom": 46,
    "United States": 47
}

majors_mapping = {
    "N/A": 0,
    "Africana Studies": 1,
    "Anthropology": 2,
    "Art History": 3,
    "Asian Studies": 4,
    "Biochemistry": 5,
    "Biology": 6,
    "Chemistry": 7,
    "Chinese": 8,
    "Classics": 9,
    "Computer Science": 10,
    "Digital and Computational Studies": 11,
    "Earth and Oceanographic Science": 12,
    "Economics": 13,
    "Education": 14,
    "English": 15,
    "Environmental Studies": 16,
    "Francophone Studies": 17,
    "French": 18,
    "Gender, Sexuality, and Women's Studies": 19,
    "German": 20,
    "Government and Legal Studies": 21,
    "Hispanic Studies": 22,
    "History": 23,
    "Italian Studies": 24,
    "Japanese": 25,
    "LCL Studies": 26,
    "Latin American Studies": 27,
    "Mathematics": 28,
    "Middle Eastern and North African Studies": 29,
    "Music": 30,
    "Neuroscience": 31,
    "Philosophy": 32,
    "Physics": 33,
    "Psychology": 34,
    "REE Studies": 35,
    "Religion": 36,
    "Romance Language and Literatures": 37,
    "Russian": 38,
    "Sociology": 39,
    "Theater and Dance": 40,
    "Visual Arts": 41
}


class_mapping = {
    "2029": 0,
    "2028": 1,
    "2027": 2,
    "2026": 3,
}